### PR TITLE
feat: integrate `pagefind` search functionality

### LINKED ISSUE #1204: [FEATURE] Add Support Pagefind search engines
### Describe the feature you want 描述你的功能需求

Doit current uses `algolia` and `fuse` as search engines. With `fuse` if the same keyword appears multiple times in the same post, that post will be listed multiple times in the search results, and the index file for `fuse` is relatively large. I tried Pagefind, and this issue does not occur. However, I am not familiar with front-end development, so I don't know how to add Pagefind to the search engines .
Currently, I can just create new HTML files in the `static` directory to use Pagefind, but there are still some problems. For example, the Doit theme places the rendered HTML directly in the public root directory, unlike Hugo's native approach of placing it in the public/post directory. As a result, Pagefind can only index all HTML files in the public directory, including directories like categories, posts, tags, and series. This leads to indexing of search keywords if they are included in categories, posts, tags, or series.
### `fuse` search result
alt text

### `Pagefind`  search result
alt text

### Useful reference 有价值的参考
https://pagefind.app/
https://zenn.dev/k1350/articles/42c13020038d4c

### PR DESCRIPTION
**Pull request by 713b76b7-2247-4bd5-98a7-014226363f9b**
Close #1204

You can create pagefind index for example site with `npx pagefind --site ./exampleSite/public`.

### Summary

- Add support for `pagefind` search type
- Update search configuration to include `pagefind` as an option
- Modify search logic to handle `pagefind` initialization and usage
- Update search result processing to integrate with `pagefind`
- Add logging for search results
- Refactor search type handling in templates
- Update documentation and configuration examples to reflect new search options

### CODE REVIEW

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
It is still an early stage implementation, please do not merge yet.

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
### fuse
SCR-20240713-luzp

### pagefind
SCR-20240713-lvlx

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Sorry for coming late, been busy with some personal stuff recently

@HEIGE-PCloud Do you want to set pagefind as default search engine? If so I will modify the github action file

**Comment by HEIGE-PCloud** [comment]
Probably not, as it involves an extra build step which will make it a breaking change. I would prefer to keep fuse as the default one as is.

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Understood, I will squash the commits tonight

**Review by HEIGE-PCloud — APPROVED** [review]

**Pull request merged**
