### PR TITLE
feat: Support tabs and tab shortcode

### LINKED ISSUE #457: [FEATURE] tab shortcodes
### Describe the feature you want 描述你的功能需求

- New Feature
  请问可以添加一个选项卡功能吗？写教程博客的时候经常会用到多种选择，比如：
  图片
  这样就很优雅

### Useful reference 有价值的参考
效果可以参考：
https://hugo-dynamic-tabs.netlify.app/

现有的github仓库：
https://github.com/rvanhorn/hugo-dynamic-tabs

### PR DESCRIPTION
**Pull request by HEIGE-PCloud**
Another attempt using 

https://github.com/github/tab-container-element

See https://do-it-git-feat-tab-pcloud.vercel.app/tab-tests/ for preview

## Task list:

- [x] Documentation
- [x] Styling
  - [x] Configure DoIt's color palette in Tailwind CSS
- [x] Features
  - [x] Tab
  - [x] DefaultTab option

### CODE REVIEW

**Comment by HEIGE-PCloud** [comment]
Any suggestion of visual design for the shortcode will be much appreciated!

**Comment by eallion** [comment]
IMO The contrast of the border-color is too high.

**Comment by HEIGE-PCloud** [comment]
This branch is ready for review! I plan to merge it at the end of today (UTC time) if everything goes well.

**Comment by eallion** [comment]
LGTM

**Pull request merged**
