### PR TITLE
feat: add edit this page link

### LINKED ISSUE #322: [FEATURE] Edit this page
### Describe the feature you want

- Feature 1: It would be great to add a link or button where clicking on the source code file is linked so that it can be edited similar to what is shown in readthedocs.io:

Screenshot_20211031_025741

It should go in the bottom section where it says "Read Markdown" or next to the commit hash:

Screenshot_20211031_030757

The url should be configurable in config.toml:

```toml
edit_url = "https://github.com/HEIGE-PCloud/DoIt"
```

Also you might need more information to generate the url, for example mkdocs adds the edit_uri parameter: https://www.mkdocs.org/user-guide/configuration/#edit_uri

For example for the post: `https://hugodoit.pages.dev/basic-markdown-syntax` the link should be `https://github.com/HEIGE-PCloud/DoIt/edit/main/exampleSite/content/posts/basic-markdown-syntax/index.en.md` from which it follows that 3 parameters are needed:

- repo_url: `https://github.com/HEIGE-PCloud/DoIt`
- edit path: `edit/main`
- relative path: `exampleSite/content/posts/basic-markdown-syntax/index.en.md`

FORMAT: `{repo_url}/{edit_path}/{relative_path}`

In bitbucket the format is: `https://bitbucket.org/user/repo/src/master/{filename}?mode=edit`

so the most generic thing should be:

FORMAT: `{repo_url}/{pre}/{relative_path}/{pos}`

Maybe you should use the "gitRepo" field and add the extra fields under "params":

https://github.com/HEIGE-PCloud/DoIt/blob/731d671d5532b21e2d2556984aa9a2d9f1a58d53/exampleSite/config.toml#L505-L531

### Useful reference

- https://discourse.gohugo.io/t/how-to-implement-edit-this-page-on-github/1166
- https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html
- https://www.mkdocs.org/user-guide/configuration/#edit_uri

### PR DESCRIPTION
**Pull request by HEIGE-PCloud**
Close #322

### CODE REVIEW

**Comment by HEIGE-PCloud** [comment]
@eyllanesc Check this out :) https://do-it-git-dev-edit-page-pcloud.vercel.app/theme-documentation-basics

**Comment by HEIGE-PCloud** [comment]
I decide to use a magic variable `{path}` instead of `%v` to specify the relative path, and use `replace` instead of `printf` to process the URL. So the user can now set a specific URL for each individual page.

**Comment by eyllanesc** [comment]
Could you explain to me with an example the phrase: *So the user can now set a specific URL for each individual page.*?

**Comment by HEIGE-PCloud** [comment]
> Could you explain to me with an example the phrase: _So the user can now set a specific URL for each individual page._?

The point is to detach the `.File.Path` from the `linkToEdit`. 

For example, you can have this configuration in your config.toml

```toml
    linkToEdit = "https://github.com/HEIGE-PCloud/DoIt/edit/main/exampleSite/content/{path}"
```

And for one special post, you want to set the `linkToEdit` to something else for whatever reason. You just set the `linkToEdit` to a new value in the front matter, and use `{path}` for `.File.Path` if needed.

With the `printf` and `%v` implementation, set it to something like

- `linkToEdit = "https://github.com/a/url/without/path"`
- `linkToEdit = "https://github.com/a/url/with/multiple/path?path"`

is impossible.

This change just adds a little bit more flexibility and does not affect anything else.

**Comment by eyllanesc** [comment]
Okay, I understand.

**Pull request merged**
