### PR TITLE
Add support for linking articles from external site

### PR DESCRIPTION
**Pull request by renzhamin**
- Adding a property `external` in the front matter will link the article from the url provided in external variable
- The content can be something as simple as "Read the article [here](link)"
- featuredImage still has to be provided if required
- A partial `articleLink.html` is used to wrap all instances where a article link is listed
- Articles from external site will be opened in a new tab

https://user-images.githubusercontent.com/57265942/233763538-ba2cd7ef-3b0c-413c-9a81-53b6da7461d5.mp4

- The first article is the one from external site, you can see this change of href is reflected on all the places where articles are listed

### CODE REVIEW

**Comment by HEIGE-PCloud** [comment]
Will everything be easier if we just set an [HTML redirect](https://www.w3docs.com/snippets/html/how-to-redirect-a-web-page-in-html.html)?

```html
<meta http-equiv="Refresh" content="0; url='https://www.example.com'" />
```

I don't know for sure, this might be a bit slower than directly changing the links, but seems less error prone.

**Comment by HEIGE-PCloud** [comment]
The current implementation seems very fragile. For example the navigation on the bottom of each post still navigates to the original page

image

and if you just visit the url of the post which is "external", you still get to see the original post.

And I am not sure whether we really need a "theme level" support for this feature - you paste this `<meta http-equiv="Refresh" content="0; url='https://www.example.com'" />` to the beginning of the markdown file you want to mark as "external", you are done. If you dislike the "flash" before redirecting, then some blocking JavaScript code will do the trick.

**Comment by renzhamin** [comment]
> The current implementation seems very fragile. For example the navigation on the bottom of each post still navigates to the original page
> 
> image
> 
> and if you just visit the url of the post which is "external", you still get to see the original post.
> 
> And I am not sure whether we really need a "theme level" support for this feature - you paste this `<meta http-equiv="Refresh" content="0; url='https://www.example.com'" />` to the beginning of the markdown file you want to mark as "external", you are done. If you dislike the "flash" before redirecting, then some blocking JavaScript code will do the trick.

Doing a refresh will get the user out of the site, which is not ideal
I have thought about it but there's no workaround other than putting something like "Read the article [here](link)" for next posts to work
Because if we use the external link here then you can't go to the post after the next post and it also compromises the purpose of keeping the user in the main site
If you are still skeptical, the feature doesn't interrupt anything else, things will change only when "external" property is set, which can be made an experimental feature

**Comment by HEIGE-PCloud** [comment]
After thoroughly reviewing your implementation, I have decided to close this pull request for the time being. The main reasons for this decision include the fact that the proposed feature may not be used by a significant number of users, making it less of a priority at this time. Additionally, the current implementation does not integrate smoothly with the existing architecture of the project, which could potentially cause future issues in terms of compatibility and stability. Also, the added complexity and maintenance cost associated may outweigh its potential benefits.

For your particular use case, I recommend copying the source from dev.to to your Hugo site and add a link to the original article. Or maybe consider the [showcase shortcode](https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#showcase). I admit they are sub-optimal, I'm open to revisiting this feature in the future when we have thoroughly considered its implementation details to ensure its successful integration. Thank you once again for your valuable contribution.

**Pull request closed without merging**
