### PR TITLE
Fix that keywords are not displayed in SEO information

### PR DESCRIPTION
**Pull request by ghost**
1. Fix that keywords are not displayed in SEO information.
2. Standardize the writing of keywords.

### CODE REVIEW

**Comment by HEIGE-PCloud** [comment]
https://developers.google.com/search/docs/advanced/crawling/special-tags

Well, at least Google does not use meta keywords for SEO...

**Comment by HEIGE-PCloud** [comment]
From the information I found, the meta keyword is pretty much deprecated by all major search engines and does not seem to bring any benefits to the SEO.

Closing this.

**Comment by eyllanesc** [comment]
@BahuangShanren On the other hand, I don't see the logic that keywords, which was a list of strings, convert it to a single string. Isn't it better to use [delimiter](https://gohugo.io/functions/delimit/) to convert the list to a string in the source code?

**Comment by HEIGE-PCloud** [comment]
Actually, the keywords option is not really used anywhere. I should probably remove it from the sample config.

**Comment by ghost** [comment]
> From the information I found, the meta keyword is pretty much deprecated by all major search engines and does not seem to bring any benefits to the SEO.
> 
> Closing this.

Sorry, my understanding of SEO seems to be lagging behind.

> @BahuangShanren On the other hand, I don't see the logic that keywords, which was a list of strings, convert it to a single string. Isn't it better to use [delimiter](https://gohugo.io/functions/delimit/) to convert the list to a string in the source code?

Because the effect of `keywords = ["Theme", "Hugo"]` is `<meta name="keywords" content="[Theme Hugo]">`, and the effect of `keywords = "Theme,Hugo"` is `<meta name="keywords" content="Theme,Hugo">`.
I see that many websites have keywords like `<meta name="keywords" content="keyword 1,keyword 2">`.
However, reminded by PCloud, I found that most websites have given up using keywords.

**Pull request closed without merging**
