### PR TITLE
perf: bilibili shortcode

### PR DESCRIPTION
**Pull request by eallion**
Migrate bilibli player `//player.bilibili.com/player.html` to `//www.bilibili.com/blackboard/html5mobileplayer.html` 

It's cleaner, and can also control `autoplay` and `muted`

### CODE REVIEW

**Comment by HEIGE-PCloud** [comment]
I am not sure about this one, the functionalities of these two players seem to be quite different. The `html5mobileplayer` does not support keyboard shortcut and does not link to the original video on Bilibili.

It might be a good idea to keep `player` on desktop and use `html5mobileplayer` only on mobile (device with window size < 680px), but that needs extra JavaScript to do a conditional loading...

**Comment by eallion** [comment]
IMO If I cannot default to `muted` and disable `autoplay`, it is considered impolite behavior. Currently, only `html5mobileplayer` can achieve this. It can also adapt the desktop version. 

I cleared the cache and opened the DEMO https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#bilibili page in Chrome's privacy mode. It still plays automatically and there is external sound. This is NSFW information.

**Comment by HEIGE-PCloud** [comment]
I think you can add `autoplay=0` to the url to disable auto-play. We can add auto-play control as another parameter to the shortcode.

i.e.

```html
    <iframe
      src="//player.bilibili.com/player.html?bvid={{ .Get `id` }}&page={{ .Get `p` | default 1 }}&autoplay=0"
      scrolling="no"
      border="0"
      frameborder="no"
      framespacing="0"
      allowfullscreen="true"
    ></iframe>
```

**Comment by eallion** [comment]
Okay, I will handle this.

**Pull request closed without merging**
