### PR TITLE
feat: Search jump

### LINKED ISSUE #1004: [FEATURE] How to open search results in a new window
### Describe the feature you want 描述你的功能需求

How to open search results in a new window or in a newtab.

### Useful reference 有价值的参考

_No response_

### PR DESCRIPTION
**Pull request by 713b76b7-2247-4bd5-98a7-014226363f9b**
fix #1004

### CODE REVIEW

**Comment by HEIGE-PCloud** [comment]
This is not quite what I was thinking… I think the proper way to do it is to make the title (or the entire block) of every search result an a tag. So the user can click to navigate in place or control + click to open in a new tab.

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
I see, will look into it later tonight

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Do a little modification, my idea is that since the suggestion title will be highlighted while hovering, clicking the title to jump to the link will be more intuitive. Btw just set the cursor type of suggestion context from text to default, it's weird with the text cursor but unable to perform copy on it...

https://github.com/HEIGE-PCloud/DoIt/assets/70063177/bf2ca425-790c-40d2-bde9-9a8939274e1d

**Review by HEIGE-PCloud — CHANGES_REQUESTED** [review]
@Sped0n Good job!

There is just one small problem, the search result probably should not disappear on click if we change the behaviour to "click the title to jump".

https://github.com/HEIGE-PCloud/DoIt/assets/52968553/63562b7b-a397-4f4e-a280-1cafa5ba3574

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
the version of `autocomplete.js` is way too old, can't even find a decent documentation for v0.38, had to fiddle around with some hacky black magic🥲

**Comment by eallion** [comment]
Great Job!

**Comment by HEIGE-PCloud** [comment]
> the version of `autocomplete.js` is way too old, can't even find a decent documentation for v0.38, had to fiddle around with some hacky black magic🥲

Yeah we should probably rewrite the search someday...

**Review by HEIGE-PCloud — APPROVED** [review]

**Pull request merged**
